### ISSUE TITLE
Cannot run pretrained models

### ISSUE THREAD

**Issue by Gigibulid** [facebookresearch/FaderNetworks#9]
Hi, I was not able to run the pre-trained models. In particular, I tried to use only one image from CelebA dataset and I got this error:
(venv) D:\PycharmProjects\FaderNetwork\venv>python interpolate.py --model_path models/young.pth --n_images 10 --n_interpolations
 10 --alpha_min 10.0 --alpha_max 10.0 --output_path young.png

INFO - 08/04/18 01:01:49 - 0:00:00 - 1 / 0 / 0 images with attributes for train / valid / test sets
Traceback (most recent call last):
  File "interpolate.py", line 64, in <module>
    data, attributes = load_images(params)
  File "D:\PycharmProjects\FaderNetwork\venv\src\loader.py", line 82, in load_images
    log_attributes_stats(train_attributes, valid_attributes, test_attributes, params)
  File "D:\PycharmProjects\FaderNetwork\venv\src\loader.py", line 39, in log_attributes_stats
    logger.debug('Valid %s: %s' % (attr_name, ' / '.join(['%.5f' % valid_attributes[:, k + i].mean() for i in range(n_cat)])))
  File "D:\PycharmProjects\FaderNetwork\venv\src\loader.py", line 39, in <listcomp>
    logger.debug('Valid %s: %s' % (attr_name, ' / '.join(['%.5f' % valid_attributes[:, k + i].mean() for i in range(n_cat)])))
IndexError: too many indices for tensor of dimension 1

Could you please help me?

**Comment by Rubiel1** [comment]
Hi @Gigibulid  did you solve your problem? I am working with 100 images and I get: 
```
  warnings.warn(msg, SourceChangeWarning)
INFO - 04/22/20 18:39:46 - 0:00:25 - 100 / 0 / 0 images with attributes for train / valid / test sets
/home/ericd/tests/FaderNetworks/src/loader.py:140: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(batch_x, volatile=True), Variable(batch_y, volatile=True)
Traceback (most recent call last):
  File "interpolate.py", line 96, in <module>
    interpolations.append(get_interpolations(ae, images, attributes, params))
  File "interpolate.py", line 72, in get_interpolations
    enc_outputs = ae.encode(images)
  File "/home/ericd/tests/FaderNetworks/src/model.py", line 106, in encode
    enc_outputs.append(layer(enc_outputs[-1]))
  File "/home/ericd/anaconda/envs/myPytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ericd/anaconda/envs/myPytorch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/ericd/anaconda/envs/myPytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ericd/anaconda/envs/myPytorch/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 106, in forward
    self.training or not self.track_running_stats,
  File "/home/ericd/anaconda/envs/myPytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats'

```

**Comment by Rubiel1** [comment]
Apparently my problem has to do with the Pytorch version, perhaps this should be on dependencies. https://discuss.pytorch.org/t/batchnorm2d-object-has-no-attribute-track-running-stats/17525
